version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: urbe_postgis
    restart: always
    environment:
      POSTGRES_USER: urbe
      POSTGRES_PASSWORD: urbe123
      POSTGRES_DB: urbe_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: urbe_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@urbe.in
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
